### ISSUE TITLE
Support sending to more types of addresses 

### ISSUE THREAD

**Issue by siegfried** [ADAOcommunity/round-table#102]
## Byron Address

Which is used by major crypto exchanges.

## Enterprise Address

Which is supposed to be used by crypto exchanges so let's get it supported as well.

**Comment by rodrigomd94** [comment]
I tested enterprise addresses and they seem to work fine. They're basically an address with only the payment part if I understand correctly.

**Comment by siegfried** [comment]
@rodrigomd94 what address did you use?

**Comment by rodrigomd94** [comment]
> @rodrigomd94 what address did you use?

I generated one using pycardano: https://pycardano.readthedocs.io/en/latest/guides/address.html

**Comment by siegfried** [comment]
Fixed by #106
