### ISSUE TITLE
Forced to refresh to sign 2 different multi-signature transactions

### ISSUE THREAD

**Issue by kylixafonso** [ADAOcommunity/round-table#136]
### Summary
When signing two different transactions imported from CBOR strings, the required signatures aren't updated from the first to the second transaction - in the sense that if both transactions require overlapping signatures, those overlapping signatures are still green after reaching the second transaction when realistically they should be grayed out because they haven't been used to sign that transaction.

**Comment by siegfried** [comment]
Fixed in #137. Please retry.
