### ISSUE TITLE
Flooding Graphql Dandelion API Calls on /treasuries/{TREASURY}

### ISSUE THREAD

**Issue by ScriptAlchemist** [ADAOcommunity/round-table#87]
If you keep a treasury open on a page URL similar to

https://roundtable.theadao.io/treasuries/{TREASURY}

You can upload your own treasury and go to that treasury page. About every ~5 seconds it does a call to Dandelion. I only noticed it because i left the page open long enough. I was being rejected once I got back to the computer.

Haven't found the reason for it yet. Just noting it.

**Comment by siegfried** [comment]
Because it is live query designed.
